CREATE TABLE categories_medicament
(
    categorie_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categorie_code        VARCHAR(20)                             NOT NULL,
    categorie_libelle     VARCHAR(100)                            NOT NULL,
    categorie_description TEXT,
    CONSTRAINT pk_categories_medicament PRIMARY KEY (categorie_id)
);

CREATE TABLE commandes_fournisseur
(
    commande_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fournisseur_id                  BIGINT                                  NOT NULL,
    createur_id                     BIGINT                                  NOT NULL,
    valideur_id                     BIGINT,
    commande_reference              VARCHAR(30)                             NOT NULL,
    commande_statut                 VARCHAR(30)                             NOT NULL,
    commande_montant_total_ht       DECIMAL(14, 2),
    commande_date_commande          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    commande_date_envoi             TIMESTAMP WITHOUT TIME ZONE,
    commande_date_reception         TIMESTAMP WITHOUT TIME ZONE,
    commande_date_livraison_estimee date,
    commande_notes                  TEXT,
    CONSTRAINT pk_commandes_fournisseur PRIMARY KEY (commande_id)
);

CREATE TABLE fournisseurs
(
    fournisseur_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fournisseur_raison_sociale        VARCHAR(200)                            NOT NULL,
    fournisseur_email                 VARCHAR(150),
    fournisseur_telephone             VARCHAR(25),
    fournisseur_adresse               TEXT,
    fournisseur_delai_livraison_jours INTEGER,
    fournisseur_est_actif             BOOLEAN                                 NOT NULL,
    fournisseur_cree_le               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_fournisseurs PRIMARY KEY (fournisseur_id)
);

CREATE TABLE lignes_commande
(
    ligne_commande_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    commande_id                          BIGINT                                  NOT NULL,
    medicament_id                        BIGINT                                  NOT NULL,
    ligne_commande_quantite_commandee    INTEGER                                 NOT NULL,
    ligne_commande_quantite_recue        INTEGER                                 NOT NULL,
    ligne_commande_prix_achat_ht         DECIMAL(10, 2),
    ligne_commande_lot_numero_recu       VARCHAR(50),
    ligne_commande_date_peremption_recue date,
    ligne_commande_date_fabrication_recue date,
    CONSTRAINT pk_lignes_commande PRIMARY KEY (ligne_commande_id)
);

CREATE TABLE lignes_vente
(
    ligne_vente_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vente_id                       BIGINT                                  NOT NULL,
    medicament_id                  BIGINT                                  NOT NULL,
    lot_id                         BIGINT                                  NOT NULL,
    ligne_vente_quantite           INTEGER                                 NOT NULL,
    ligne_vente_prix_unitaire_ttc  DECIMAL(10, 2)                          NOT NULL,
    ligne_vente_prix_unitaire_ht   DECIMAL(10, 2)                          NOT NULL,
    ligne_vente_taux_tva           DECIMAL(5, 2)                           NOT NULL,
    ligne_vente_sous_total_ttc     DECIMAL(12, 2)                          NOT NULL,
    ligne_vente_taux_remboursement DECIMAL(5, 2)                           NOT NULL,
    CONSTRAINT pk_lignes_vente PRIMARY KEY (ligne_vente_id)
);

CREATE TABLE lots_stock
(
    lot_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    medicament_id         BIGINT                                  NOT NULL,
    commande_id           BIGINT,
    lot_numero            VARCHAR(50)                             NOT NULL,
    lot_quantite_recue    INTEGER                                 NOT NULL,
    lot_quantite_restante INTEGER                                 NOT NULL,
    lot_date_fabrication  date,
    lot_date_peremption   date,
    lot_prix_achat_ht     DECIMAL(10, 2)                          NOT NULL,
    lot_est_actif         BOOLEAN                                 NOT NULL,
    lot_cree_le           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    lot_cree_par_id       BIGINT,
    CONSTRAINT pk_lots_stock PRIMARY KEY (lot_id)
);

CREATE TABLE medicaments
(
    medicament_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categorie_id                     BIGINT                                  NOT NULL,
    fournisseur_id                   BIGINT,
    medicament_code_cip              VARCHAR(13)                             NOT NULL,
    medicament_denomination          VARCHAR(200)                            NOT NULL,
    medicament_dci                   VARCHAR(200)                            NOT NULL,
    medicament_forme_galenique       VARCHAR(50)                             NOT NULL,
    medicament_dosage                VARCHAR(50),
    medicament_statut_legal          VARCHAR(30)                             NOT NULL,
    medicament_prix_vente_ttc        DECIMAL(10, 2)                          NOT NULL,
    medicament_prix_achat_ht         DECIMAL(10, 2)                          NOT NULL,
    medicament_taux_tva              DECIMAL(5, 2)                           NOT NULL,
    medicament_stock_quantite_totale INTEGER                                 NOT NULL,
    medicament_stock_seuil_alerte    INTEGER                                 NOT NULL,
    medicament_emplacement           VARCHAR(50),
    medicament_fabricant             VARCHAR(150),
    medicament_est_remboursable_ss   BOOLEAN                                 NOT NULL,
    medicament_taux_remboursement_ss DECIMAL(5, 2),
    medicament_est_disponible        BOOLEAN                                 NOT NULL,
    medicament_cree_le               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    medicament_modifie_le            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_medicaments PRIMARY KEY (medicament_id)
);

CREATE TABLE mouvements_stock
(
    mouvement_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    medicament_id             BIGINT                                  NOT NULL,
    lot_id                    BIGINT,
    vente_id                  BIGINT,
    commande_id               BIGINT,
    mouvement_type            VARCHAR(30)                             NOT NULL,
    mouvement_quantite        INTEGER                                 NOT NULL,
    mouvement_motif           TEXT,
    mouvement_effectue_le     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    mouvement_effectue_par_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_mouvements_stock PRIMARY KEY (mouvement_id)
);

CREATE TABLE ordonnances
(
    ordonnance_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id                   BIGINT                                  NOT NULL,
    ordonnance_numero            VARCHAR(50)                             NOT NULL,
    ordonnance_medecin_nom       VARCHAR(150)                            NOT NULL,
    ordonnance_medecin_rpps      VARCHAR(20),
    ordonnance_date_prescription date                                    NOT NULL,
    ordonnance_date_validite     date,
    ordonnance_statut            VARCHAR(30)                             NOT NULL,
    ordonnance_fichier_scan_url  VARCHAR(500),
    ordonnance_a_tiers_payant    BOOLEAN                                 NOT NULL,
    ordonnance_saisie_le         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ordonnance_saisie_par_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_ordonnances PRIMARY KEY (ordonnance_id)
);

CREATE TABLE patients
(
    patient_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_nom               VARCHAR(100)                            NOT NULL,
    patient_prenom            VARCHAR(100)                            NOT NULL,
    patient_date_naissance    date,
    patient_telephone         VARCHAR(25),
    patient_num_secu_sociale  VARCHAR(15),
    patient_mutuelle          VARCHAR(100),
    patient_taux_mutuelle     DECIMAL(5, 2),
    patient_allergies_connues TEXT,
    patient_cree_le           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);

CREATE TABLE utilisateurs
(
    utilisateur_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    utilisateur_nom           VARCHAR(100)                            NOT NULL,
    utilisateur_prenom        VARCHAR(100)                            NOT NULL,
    utilisateur_email         VARCHAR(150)                            NOT NULL,
    utilisateur_password_hash VARCHAR(255)                            NOT NULL,
    utilisateur_role          VARCHAR(30)                             NOT NULL,
    utilisateur_est_actif     BOOLEAN                                 NOT NULL,
    utilisateur_cree_le       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    utilisateur_modifie_le    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_utilisateurs PRIMARY KEY (utilisateur_id)
);

CREATE TABLE ventes
(
    vente_id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id                       BIGINT,
    ordonnance_id                    BIGINT,
    vendeur_id                       BIGINT                                  NOT NULL,
    vente_reference                  VARCHAR(30)                             NOT NULL,
    vente_montant_total_ht           DECIMAL(12, 2)                          NOT NULL,
    vente_montant_tva                DECIMAL(12, 2)                          NOT NULL,
    vente_montant_total_ttc          DECIMAL(12, 2)                          NOT NULL,
    vente_montant_rembourse_ss       DECIMAL(10, 2)                          NOT NULL,
    vente_montant_rembourse_mutuelle DECIMAL(10, 2)                          NOT NULL,
    vente_montant_paye_client        DECIMAL(10, 2)                          NOT NULL,
    vente_mode_paiement              VARCHAR(30)                             NOT NULL,
    vente_statut                     VARCHAR(20)                             NOT NULL,
    vente_effectuee_le               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    vente_annulee_le                 TIMESTAMP WITHOUT TIME ZONE,
    vente_annulee_par_id             BIGINT,
    CONSTRAINT pk_ventes PRIMARY KEY (vente_id)
);

ALTER TABLE categories_medicament
    ADD CONSTRAINT uc_categories_medicament_categorie_code UNIQUE (categorie_code);

ALTER TABLE commandes_fournisseur
    ADD CONSTRAINT uc_commandes_fournisseur_commande_reference UNIQUE (commande_reference);

ALTER TABLE medicaments
    ADD CONSTRAINT uc_medicaments_medicament_code_cip UNIQUE (medicament_code_cip);

ALTER TABLE ordonnances
    ADD CONSTRAINT uc_ordonnances_ordonnance_numero UNIQUE (ordonnance_numero);

ALTER TABLE utilisateurs
    ADD CONSTRAINT uc_utilisateurs_utilisateur_email UNIQUE (utilisateur_email);

ALTER TABLE ventes
    ADD CONSTRAINT uc_ventes_vente_reference UNIQUE (vente_reference);

ALTER TABLE commandes_fournisseur
    ADD CONSTRAINT FK_COMMANDES_FOURNISSEUR_ON_CREATEUR FOREIGN KEY (createur_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE commandes_fournisseur
    ADD CONSTRAINT FK_COMMANDES_FOURNISSEUR_ON_FOURNISSEUR FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (fournisseur_id);

ALTER TABLE commandes_fournisseur
    ADD CONSTRAINT FK_COMMANDES_FOURNISSEUR_ON_VALIDEUR FOREIGN KEY (valideur_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE lignes_commande
    ADD CONSTRAINT FK_LIGNES_COMMANDE_ON_COMMANDE FOREIGN KEY (commande_id) REFERENCES commandes_fournisseur (commande_id);

ALTER TABLE lignes_commande
    ADD CONSTRAINT FK_LIGNES_COMMANDE_ON_MEDICAMENT FOREIGN KEY (medicament_id) REFERENCES medicaments (medicament_id);

ALTER TABLE lignes_vente
    ADD CONSTRAINT FK_LIGNES_VENTE_ON_LOT FOREIGN KEY (lot_id) REFERENCES lots_stock (lot_id);

ALTER TABLE lignes_vente
    ADD CONSTRAINT FK_LIGNES_VENTE_ON_MEDICAMENT FOREIGN KEY (medicament_id) REFERENCES medicaments (medicament_id);

ALTER TABLE lignes_vente
    ADD CONSTRAINT FK_LIGNES_VENTE_ON_VENTE FOREIGN KEY (vente_id) REFERENCES ventes (vente_id);

ALTER TABLE lots_stock
    ADD CONSTRAINT FK_LOTS_STOCK_ON_COMMANDE FOREIGN KEY (commande_id) REFERENCES commandes_fournisseur (commande_id);

ALTER TABLE lots_stock
    ADD CONSTRAINT FK_LOTS_STOCK_ON_LOT_CREE_PAR FOREIGN KEY (lot_cree_par_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE lots_stock
    ADD CONSTRAINT FK_LOTS_STOCK_ON_MEDICAMENT FOREIGN KEY (medicament_id) REFERENCES medicaments (medicament_id);

ALTER TABLE medicaments
    ADD CONSTRAINT FK_MEDICAMENTS_ON_CATEGORIE FOREIGN KEY (categorie_id) REFERENCES categories_medicament (categorie_id);

ALTER TABLE medicaments
    ADD CONSTRAINT FK_MEDICAMENTS_ON_FOURNISSEUR FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (fournisseur_id);

ALTER TABLE mouvements_stock
    ADD CONSTRAINT FK_MOUVEMENTS_STOCK_ON_COMMANDE FOREIGN KEY (commande_id) REFERENCES commandes_fournisseur (commande_id);

ALTER TABLE mouvements_stock
    ADD CONSTRAINT FK_MOUVEMENTS_STOCK_ON_LOT FOREIGN KEY (lot_id) REFERENCES lots_stock (lot_id);

ALTER TABLE mouvements_stock
    ADD CONSTRAINT FK_MOUVEMENTS_STOCK_ON_MEDICAMENT FOREIGN KEY (medicament_id) REFERENCES medicaments (medicament_id);

ALTER TABLE mouvements_stock
    ADD CONSTRAINT FK_MOUVEMENTS_STOCK_ON_MOUVEMENT_EFFECTUE_PAR FOREIGN KEY (mouvement_effectue_par_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE mouvements_stock
    ADD CONSTRAINT FK_MOUVEMENTS_STOCK_ON_VENTE FOREIGN KEY (vente_id) REFERENCES ventes (vente_id);

ALTER TABLE ordonnances
    ADD CONSTRAINT FK_ORDONNANCES_ON_ORDONNANCE_SAISIE_PAR FOREIGN KEY (ordonnance_saisie_par_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE ordonnances
    ADD CONSTRAINT FK_ORDONNANCES_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (patient_id);

ALTER TABLE ventes
    ADD CONSTRAINT FK_VENTES_ON_ORDONNANCE FOREIGN KEY (ordonnance_id) REFERENCES ordonnances (ordonnance_id);

ALTER TABLE ventes
    ADD CONSTRAINT FK_VENTES_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (patient_id);

ALTER TABLE ventes
    ADD CONSTRAINT FK_VENTES_ON_VENDEUR FOREIGN KEY (vendeur_id) REFERENCES utilisateurs (utilisateur_id);

ALTER TABLE ventes
    ADD CONSTRAINT FK_VENTES_ON_VENTE_ANNULEE_PAR FOREIGN KEY (vente_annulee_par_id) REFERENCES utilisateurs (utilisateur_id);